version: '3'
services:
  telegram-onedrive:
    container_name: telegram-onedrive
    image: hlf01/telegram-onedrive
    restart: always

    # If you're on Linux, use this:
    #network_mode: host
    # If you're on Windows or macOS, use this, "xxxx" is your port in server_uri:
    #ports:
       #- 8000:8000

    # volumes:
      # - /path/to/*.crt:/telegram-onedrive/server/ssl/server.crt
      # - /path/to/*.key:/telegram-onedrive/server/ssl/server.key
      # - telegram-onedrive-session:/telegram-onedrive/session

    environment:
      - server_uri=https://127.0.0.1:8080
      - tg_bot_token=6474375449:AAGl2eBfMsbCev82AVdIBANjD4L7L4iQHf8
      - tg_api_id=22147341
      - tg_api_hash=934c035fbd516eae137ea9a426f58698
      - tg_user_phone=+17206575574
      - tg_user_name=davidarnold66
      - od_client_id=166d8e2a-55f2-4a26-9838-49d9aefcc445
      - od_client_secret=cDe8Q~Mix~_V~SqxqX3c.B.q9-uA0qO26UtQic3c
      - remote_root_path=/Videos
      - delete_flag=$delete_flag(optional, true or false, default to false)
    command: python main.py

# volumes:
#   telegram-onedrive-session:
